greeting:
  message: "hello 22"
mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        auto:
          offset:
            reset: "earliest"
        topic: "words"
